STEP_COMMAND_PAUSE_LENGTH = 0.005
PROGRAM_PREVIEW_PAUSE_LENGTH = 0
IMPORTANT_PAUSE_LENGTH = 0.1
PAUSE_LENGTH = 0

CLEAR_SCREEN = FALSE
CLEAR_SCREEN_MAP_LOG = TRUE
CLEAR_SCREEN_TEAM_LOG = TRUE

SEED = 0
TOTAL_MUTATIONS = 60

PROGRAM_MUTATIONS = 10
PROGRAM_MUTATION_MAX_SIZE = 3

MAP_LOG_FILE = "display_logs/map_log"
TEAM_LOG_FILE = "display_logs/team_log"
BATTLE_LOG_FILE = "display_logs/battle_log"

MAX_STEPS = 30
