magic_skill ballistic_skill armor melee_damage magic_range ballistic_skill magics  +melee_damage2 melee_damage
ballistic_range magic_skill wounds
ballistic_skill ballistic_skill magic_skill
magics  -ballistic_skill4 ballistic_defense_skill
melee_skill melee_damage
ballistic_range ballistic_skill melee_skill ballistic_range ballistic_damage ballistic_skill wounds magic_range
ballistic_skill
ballistic_damage melee_skill ballistic_skill wounds ballistic_skill wounds ballistic_defense_skill ballistic_damage
magic_range
ballistic_damage magic_skill melee_skill magic_range ballistic_damage melee_skill magics  +magic_skill1
ballistic_range ballistic_defense_skill move
magic_range
ballistic_damage armor
wounds armor armor melee_skill ballistic_skill armor ballistic_damage magic_skill melee_damage
magics  +melee_damage5 move wounds move
ballistic_defense_skill ballistic_damage armor ballistic_range melee_damage ballistic_skill move
melee_skill armor armor ballistic_defense_skill
ballistic_range
melee_skill ballistic_skill ballistic_range magic_skill ballistic_skill ballistic_skill ballistic_defense_skill magic_skill armor
wounds magic_skill magics  -ballistic_range4 magics  -armor3
ballistic_range move
magic_range ballistic_skill ballistic_range ballistic_defense_skill
melee_skill wounds move magics  +melee_skill1 magic_range ballistic_damage ballistic_range
magic_skill ballistic_range ballistic_range melee_skill wounds
armor ballistic_range ballistic_defense_skill ballistic_defense_skill armor wounds ballistic_skill
ballistic_skill
wounds ballistic_range melee_skill melee_skill armor
magics  +ballistic_skill3 wounds ballistic_damage
magic_range melee_skill magics  +magic_range1 magic_range move
magic_range ballistic_defense_skill ballistic_damage magic_skill ballistic_range ballistic_damage
magic_skill ballistic_skill armor melee_damage magic_range ballistic_skill magics  +melee_damage2 melee_damage
ballistic_range magic_skill wounds
ballistic_skill ballistic_skill magic_skill
magics  -ballistic_skill4 ballistic_defense_skill
melee_skill melee_damage
ballistic_range ballistic_skill melee_skill ballistic_range ballistic_damage ballistic_skill wounds magic_range
ballistic_skill
ballistic_damage melee_skill ballistic_skill wounds ballistic_skill wounds ballistic_defense_skill ballistic_damage
magic_range
ballistic_damage magic_skill melee_skill magic_range ballistic_damage melee_skill magics  +magic_skill1
ballistic_range ballistic_defense_skill move
magic_range
ballistic_damage armor
wounds armor armor melee_skill ballistic_skill armor ballistic_damage magic_skill melee_damage
magics  +melee_damage5 move wounds move
ballistic_defense_skill ballistic_damage armor ballistic_range melee_damage ballistic_skill move
melee_skill armor armor ballistic_defense_skill
ballistic_range
melee_skill ballistic_skill ballistic_range magic_skill ballistic_skill ballistic_skill ballistic_defense_skill magic_skill armor
wounds magic_skill magics  -ballistic_range4 magics  -armor3
ballistic_range move
magic_range ballistic_skill ballistic_range ballistic_defense_skill
melee_skill wounds move magics  +melee_skill1 magic_range ballistic_damage ballistic_range
magic_skill ballistic_range ballistic_range melee_skill wounds
armor ballistic_range ballistic_defense_skill ballistic_defense_skill armor wounds ballistic_skill
ballistic_skill
wounds ballistic_range melee_skill melee_skill armor
magics  +ballistic_skill3 wounds ballistic_damage
magic_range melee_skill magics  +magic_range1 magic_range move
magic_range ballistic_defense_skill ballistic_damage magic_skill ballistic_range ballistic_damage
magic_skill ballistic_skill armor melee_damage magic_range ballistic_skill magics  +melee_damage2 melee_damage
ballistic_range magic_skill wounds
ballistic_skill ballistic_skill magic_skill
magics  -ballistic_skill4 ballistic_defense_skill
melee_skill melee_damage
ballistic_range ballistic_skill melee_skill ballistic_range ballistic_damage ballistic_skill wounds magic_range
ballistic_skill
ballistic_damage melee_skill ballistic_skill wounds ballistic_skill wounds ballistic_defense_skill ballistic_damage
magic_range
ballistic_damage magic_skill melee_skill magic_range ballistic_damage melee_skill magics  +magic_skill1
ballistic_range ballistic_defense_skill move
magic_range
ballistic_damage armor
wounds armor armor melee_skill ballistic_skill armor ballistic_damage magic_skill melee_damage
magics  +melee_damage5 move wounds move
ballistic_defense_skill ballistic_damage armor ballistic_range melee_damage ballistic_skill move
melee_skill armor armor ballistic_defense_skill
ballistic_range
melee_skill ballistic_skill ballistic_range magic_skill ballistic_skill ballistic_skill ballistic_defense_skill magic_skill armor
wounds magic_skill magics  -ballistic_range4 magics  -armor3
ballistic_range move
magic_range ballistic_skill ballistic_range ballistic_defense_skill
melee_skill wounds move magics  +melee_skill1 magic_range ballistic_damage ballistic_range
magic_skill ballistic_range ballistic_range melee_skill wounds
armor ballistic_range ballistic_defense_skill ballistic_defense_skill armor wounds ballistic_skill
ballistic_skill
wounds ballistic_range melee_skill melee_skill armor
magics  +ballistic_skill3 wounds ballistic_damage
magic_range melee_skill magics  +magic_range1 magic_range move
magic_range ballistic_defense_skill ballistic_damage magic_skill ballistic_range ballistic_damage
ballistic_damage melee_skill magic_range
armor armor ballistic_range wounds
wounds melee_skill ballistic_range melee_skill ballistic_skill wounds ballistic_range
ballistic_range magics  +armor2 armor ballistic_range
ballistic_range wounds move ballistic_skill magic_range
ballistic_defense_skill wounds magics  -ballistic_range5 melee_skill
armor magic_range ballistic_defense_skill ballistic_damage ballistic_range armor ballistic_damage
magics  +armor5
move ballistic_defense_skill ballistic_skill
ballistic_range melee_damage magic_skill magic_range move magic_skill
ballistic_skill melee_skill
magic_skill wounds armor wounds ballistic_skill
magic_range ballistic_skill ballistic_range
magic_range ballistic_skill melee_damage wounds wounds melee_damage ballistic_damage magic_range magic_range
ballistic_damage melee_damage melee_skill armor magics  +armor3
ballistic_damage armor magic_skill ballistic_range
magics  +ballistic_range3 ballistic_damage
ballistic_skill ballistic_range armor
ballistic_defense_skill melee_damage ballistic_defense_skill
wounds ballistic_damage wounds ballistic_damage
ballistic_defense_skill ballistic_range ballistic_damage armor magic_skill magic_range magics  -ballistic_skill1
ballistic_damage move melee_skill move armor armor
ballistic_range wounds wounds ballistic_skill armor
magic_range magic_range
ballistic_skill ballistic_damage ballistic_damage
ballistic_range ballistic_range armor ballistic_defense_skill
ballistic_range armor ballistic_defense_skill magic_skill armor wounds armor armor
ballistic_range move magics  +move2 ballistic_range
melee_damage armor ballistic_skill ballistic_defense_skill magic_range armor move ballistic_skill melee_skill
ballistic_skill magic_skill
ballistic_damage magics  -ballistic_range5
